# Generated by Django 5.0.1 on 2026-02-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_subscriptionplan_organisation_organisationmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free modules are accessible to all registered users without a subscription'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('intro', 'Free Introduction'), ('chat', 'AI Chat Mastery'), ('builder', 'Build AI-Powered Tools'), ('coding', 'Code with AI Assistant'), ('data', 'AI + Data Magic')], max_length=20),
        ),
    ]
