# Generated by Django 5.0.1 on 2026-03-31 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_module_is_free_alter_module_module_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='learning.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_emoji', models.CharField(default='💼', max_length=10)),
                ('organisation_name', models.CharField(default='LearnPulse · AI Training Division', max_length=200)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='remote', max_length=20)),
                ('contract_type', models.CharField(choices=[('contract', 'Contract'), ('full_time', 'Full-time'), ('part_time', 'Part-time')], default='contract', max_length=20)),
                ('pay_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_period', models.CharField(choices=[('hour', '/hr'), ('month', '/month'), ('year', '/year')], default='hour', max_length=10)),
                ('pay_note', models.CharField(blank=True, help_text='e.g. "Flexible hours"', max_length=100)),
                ('tags', models.JSONField(default=list, help_text='List of skill tag strings')),
                ('spots_available', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited. Used for FOMO display.', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_modules', models.ManyToManyField(blank=True, help_text='Modules a student must have a certificate for to apply', related_name='required_for_jobs', to='learning.module')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('cover_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='learning.certificate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='learning.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('job_application', 'Job Application'), ('certificate_issued', 'Certificate Issued'), ('general', 'General')], default='general', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
