# Generated by Django 5.0.1 on 2026-03-31 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_certificate_jobposting_jobapplication_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='module',
            field=models.OneToOneField(blank=True, help_text='The module this plan unlocks. Leave blank for full-bundle plans.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to='learning.module'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('module', 'Single Module'), ('bundle', 'Full Bundle')], default='bundle', max_length=20),
        ),
    ]
