# Generated by Django 5.0.1 on 2026-03-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_add_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_count', models.IntegerField(default=3200, help_text='Displayed learner count (real users + offset)')),
                ('graduates_hired', models.IntegerField(default=480)),
                ('completion_rate', models.IntegerField(default=87, help_text='Percentage 0-100')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Statistics',
                'verbose_name_plural': 'Platform Statistics',
            },
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='is_simulated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
