# Generated by Django 5.0.1 on 2026-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_platformstat_leaderboard_simulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-discount price shown struck-through. Leave blank if not discounted.', max_digits=10, null=True),
        ),
    ]
