# Generated by Django 5.0.1 on 2026-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_subscriptionplan_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency_paid',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
