# Generated by Django 5.0.1 on 2026-07-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_subscription_amount_paid_subscription_currency_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paystack_authorization_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Length of one billing cycle in days. Leave blank for lifetime (one-time) access.', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this plan can auto-renew. Only meaningful when duration_days is set.'),
        ),
    ]
