# Generated by Django 5.0.1 on 2026-08-05 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('challenge', 'Challenge Submission'), ('chatbot', 'Platform Chatbot')], db_index=True, max_length=20)),
                ('flagged', models.BooleanField(default=False, help_text='True if the prompt was blocked as suspicious/off-topic before hitting the Claude API.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'endpoint', 'created_at'], name='learning_ap_user_id_26cb3a_idx')],
            },
        ),
    ]
