# Generated by Django 5.0.1 on 2026-08-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_apiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_hash', models.CharField(db_index=True, help_text='SHA-256 of the stripped prompt text', max_length=64)),
                ('ai_response', models.TextField()),
                ('evaluation', models.JSONField(blank=True, help_text='{"score", "feedback", "passed"} once a submit has evaluated this prompt', null=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_responses', to='learning.challenge')),
            ],
            options={
                'indexes': [models.Index(fields=['challenge', 'prompt_hash'], name='learning_pr_challen_f935ef_idx')],
                'unique_together': {('challenge', 'prompt_hash')},
            },
        ),
    ]
