# Generated by Django 5.0.1 on 2026-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_promptresponsecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_seats', models.PositiveIntegerField()),
                ('max_seats', models.PositiveIntegerField(blank=True, help_text='Leave blank for an open-ended top tier (e.g. "150+ seats")', null=True)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('label', models.CharField(blank=True, help_text='e.g. "Small teams", "Enterprise"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_seats'],
            },
        ),
    ]
